// <auto-generated />
namespace Cycling.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class stringmaxadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stringmaxadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201706071524421_string-max-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
