// <auto-generated />
namespace Cycling.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingGiroDiItalia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingGiroDiItalia));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081527146_adding Giro Di Italia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
